### ISSUE TITLE
Question about how to use with docker compose

### ISSUE THREAD

**Issue by zcaudate** [lispyclouds/clj-docker-client#24]
I know this is a lower level library but I'm wondering if there was any good workflow to use this library with a docker-compose file.

**Comment by lispyclouds** [comment]
Hey @zcaudate , thanks for the question! Yes, as you said this is a low level lib akin to the official [python](https://github.com/docker/docker-py) and [go](https://godoc.org/github.com/docker/docker/client) libs to docker. docker-compose is a python lib which users docker-py to do its thing. 

I could imagine something which parses the compose YAML and uses this to make the calls. This lib on its own is not intended to directly use compose files. Maybe someone makes a more data driven docker compose setup approach! 😄

**Comment by zcaudate** [comment]
@lispyclouds ah okay. That would be a bit of work. 

For now, I'm shelling out but would like to have a better way to query services that are defined in a docker-compose file. I might revisit this later on. Thanks!

**Comment by victorb** [comment]
Not really relevant to this repository at all, but because some of us using this client are interested in docker-compose, the specification is now being worked on (was previously only for docker-compose) https://www.docker.com/blog/announcing-the-compose-specification/

Suddenly got more interesting to implement a docker-compose clojure CLI/lib (using clj-docker-client of course)

**Comment by lispyclouds** [comment]
@victorb this is super exiciting to hear!! Maybe we can think of an impl supporting both YAML an d edn. Also we can target the GraalVM native either via full native compilation or via the https://github.com/borkdude/babashka runtime. This would be really really sweet! Imagine the REPL powers now ❤️
