### ISSUE TITLE
Question: How to provide docker/run parameters?

### ISSUE THREAD

**Issue by tzach** [lispyclouds/clj-docker-client#9]
How do I provide parameters like `--name XXX`?
I did not find it in the example and code

**Comment by lispyclouds** [comment]
Its not implemented yet, but can be added. Will do it in a release soon. Thanks for reporting!

**Comment by lispyclouds** [comment]
@tzach , implementing all of the run flags would be a long process and since I'm not using a lot of them it would be great if you could list of flags you would require at the moment so that I can implement them quickly and make a release. That would help me in narrowing down the huge list. Alternatively I'm also happy to merge a PR can help out with the code if that's faster.

**Comment by olymk2** [comment]
I would also be interested in seeing other param's, in particular volume mounts, would it not be possible to take a map and pass that on to the api instead of handling each parameter individually ?

**Comment by lispyclouds** [comment]
This is possible with the 0.4.0 release which takes all params as a data map.
